[tools]
"cargo:controld-cli" = "latest"
claude = "latest"
codex = "latest"
copilot = "latest"
go = "latest"
just = "latest"
node = "latest"
"npm:agent-browser" = "latest"
"npm:defuddle-cli" = "latest"
"npm:playwright" = "latest"
"npm:pnpm" = "latest"
opencode = "latest"
pi = "latest"
ruby = "latest"
shellcheck = "latest"
zig = "latest"
zls = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
